In [1]:
import pandas as pd
import numpy as np


df = pd.read_csv("Mall_Customers.csv")

In [2]:

df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
df.shape

(200, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [6]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

# missing value

In [7]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [8]:
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [CustomerID, Gender, Age, Annual Income (k$), Spending Score (1-100)]
Index: []

In [13]:
df.columns.tolist()

['CustomerID', 'Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)']

In [12]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

cleaning

no missing value

In [51]:
print("Before:", df.shape)
df = df.drop_duplicates()
print("After:", df.shape)

Before: (200, 5)
After: (200, 5)

In [28]:
df.columns = (df.columns
              .str.lower()
              .str.strip()
              .str.replace(' ', '_')
              .str.replace(r'[^\w]', '', regex=True))

print(df.columns.tolist())

['customerid', 'gender', 'age', 'annual_income_k', 'spending_score_1100']

In [32]:

df['age'] = df['age'].astype(int)

In [33]:

df['gender'] = df['gender'].str.strip().str.capitalize()

print(df['gender'].unique())

['Male' 'Female']

In [34]:

print(df['age'].min())
print(df['age'].max())

df = df[df['age'] > 0]
df = df[df['age'] < 100]

18
70

Verify

In [53]:

print("Shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nDuplicates:", df.duplicated().sum())
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\nSample data:")
df.head()

Shape: (200, 5)

Missing values:
 customerid             0
gender                 0
age                    0
annual_income_k        0
spending_score_1100    0
dtype: int64

Duplicates: 0

Column names: ['customerid', 'gender', 'age', 'annual_income_k', 'spending_score_1100']

Data types:
 customerid              int64
gender                 object
age                     int64
annual_income_k         int64
spending_score_1100     int64
dtype: object

Sample data:

   customerid  gender  age  annual_income_k  spending_score_1100
0           1    Male   19               15                   39
1           2    Male   21               15                   81
2           3  Female   20               16                    6
3           4  Female   23               16                   77
4           5  Female   31               17                   40

In [55]:
df.to_csv("cleaned_mall_customers.csv", index=False)
print("File saved successfully!")

File saved successfully!